### ISSUE TITLE
AS6

### ISSUE THREAD

**Issue by Chris72er** [hilch/PLC-data-trace#1]
Unfortunately, the project can no longer be compiled with AS6.
![trace](https://github.com/user-attachments/assets/46cfad7b-2671-42f1-b675-ad0aef7c25d1)
.

**Comment by Chris72er** [comment]
I fix it. By inserting the code line ,,unsigned long bur_heap_size = 0xFFFF; '' it works again.

**Comment by hilch** [comment]
Thanks @Chris72er !
I changed language to C++ and renamed master branch to 'AS4X'. 
Additionally you'll find a second branch 'AS6X'
